### ISSUE TITLE
random errors

### ISSUE THREAD

**Issue by laerm0** [RafalBuchner/StemThickness#25]
Here's a bunch of stuff from the macro window:

```
ERROR: crossPoint == ON CURVE POINT!!!!
ERROR: crossPoint == ON CURVE POINT!!!!
ERROR: crossPoint == ON CURVE POINT!!!!
ERROR: crossPoint == ON CURVE POINT!!!!
ERROR: crossPoint == ON CURVE POINT!!!!
ERROR: crossPoint == ON CURVE POINT!!!!
ERROR: crossPoint == ON CURVE POINT!!!!
ERROR: crossPoint == ON CURVE POINT!!!!
ERROR: crossPoint == ON CURVE POINT!!!!
ERROR: crossPoint == ON CURVE POINT!!!!
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1158, in drawForegroundForLayer_options_
  File "StemThickness.py", line 101, in foreground
    self.drawCrossingsForData(closestData)
  File "StemThickness.py", line 172, in drawCrossingsForData
    FirstCrossPointA = NSPoint(crossPoints[i].x,crossPoints[i].y)           #blue
  File "_convenience.py", line 459, in __getitem__objectAtIndex_
    raise IndexError("list index out of range")
IndexError: list index out of range
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1158, in drawForegroundForLayer_options_
  File "StemThickness.py", line 96, in foreground
    closestData = self.calcClosestInfo(layer, crossHairCenter)
  File "StemThickness.py", line 263, in calcClosestInfo
    n = math.floor(closestPathTime)
TypeError: a float is required
```

Let me know if you'd like help diagnosing this. Thanks.

**Comment by laerm0** [comment]
Hi, I've got a new error and I think I have nailed it down. Here's what I see:

```
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1158, in drawForegroundForLayer_options_
  File "plugin.py", line 104, in foreground
    self.drawCrossingsForData(closestData)
  File "plugin.py", line 175, in drawCrossingsForData
    FirstCrossPointA = NSPoint(crossPoints[i].x,crossPoints[i].y)           #blue
  File "_convenience.py", line 459, in __getitem__objectAtIndex_
    raise IndexError("list index out of range")
IndexError: list index out of range
```

I get this error when using the Select tool. It seems to occur when I have a node selected and am moving it with the cursor over a stem (show the plugin shows the value). It seems like it happens when I have this plugin and the Show-Stems plugin from @Mark2Mark. (Yes, I know this feels a little redundant.)

Maybe something in glyphsLib changed?
